//! LSP client trait and error types.
//!
//! Defines the [`LspClient`] trait, which is the core abstraction for all tool
//! handlers in the MCP server. The real implementation talks to `lake serve`
//! over stdio; tests use [`MockLspClient`] (generated by mockall).

use async_trait::async_trait;
use serde_json::Value;
use std::path::{Path, PathBuf};

/// Errors from LSP client operations.
#[derive(Debug, thiserror::Error)]
pub enum LspClientError {
    /// A transport-level error (I/O, framing, process).
    #[error("Transport error: {0}")]
    Transport(#[from] crate::error::TransportError),

    /// The LSP server returned a JSON-RPC error response.
    #[error("LSP error: {message}")]
    LspError {
        /// JSON-RPC error code.
        code: i64,
        /// Human-readable error message.
        message: String,
    },

    /// A request timed out waiting for a response or event.
    #[error("Timeout waiting for {operation}")]
    Timeout {
        /// Description of what was being waited on.
        operation: String,
    },

    /// An operation was attempted on a file that has not been opened.
    #[error("File not open: {0}")]
    FileNotOpen(String),

    /// The client has not been initialized yet.
    #[error("Client not initialized")]
    NotInitialized,
}

/// Abstract LSP client trait for testability via mockall.
///
/// All tool handlers work against `dyn LspClient`, and the test suite uses
/// `MockLspClient` to verify behaviour without a real Lean server.
#[cfg_attr(test, mockall::automock)]
#[async_trait]
pub trait LspClient: Send + Sync {
    /// Get the project path this client is connected to.
    fn project_path(&self) -> &Path;

    /// Open a file in the LSP server.
    async fn open_file(&self, relative_path: &str) -> Result<(), LspClientError>;

    /// Open a file, forcing a reopen if already open.
    async fn open_file_force(&self, relative_path: &str) -> Result<(), LspClientError>;

    /// Get cached file content.
    async fn get_file_content(&self, relative_path: &str) -> Result<String, LspClientError>;

    /// Apply incremental changes to a file.
    async fn update_file(
        &self,
        relative_path: &str,
        changes: Vec<Value>,
    ) -> Result<(), LspClientError>;

    /// Replace entire file content.
    async fn update_file_content(
        &self,
        relative_path: &str,
        content: &str,
    ) -> Result<(), LspClientError>;

    /// Close files in the LSP server.
    async fn close_files(&self, paths: &[String]) -> Result<(), LspClientError>;

    /// Get diagnostics for a file, waiting for inactivity.
    async fn get_diagnostics(
        &self,
        relative_path: &str,
        start_line: Option<u32>,
        end_line: Option<u32>,
        inactivity_timeout: Option<f64>,
    ) -> Result<Value, LspClientError>;

    /// Get interactive diagnostics (Lean extension).
    async fn get_interactive_diagnostics(
        &self,
        relative_path: &str,
        start_line: Option<u32>,
        end_line: Option<u32>,
    ) -> Result<Vec<Value>, LspClientError>;

    /// Get proof goal at position.
    async fn get_goal(
        &self,
        relative_path: &str,
        line: u32,
        column: u32,
    ) -> Result<Option<Value>, LspClientError>;

    /// Get term goal at position.
    async fn get_term_goal(
        &self,
        relative_path: &str,
        line: u32,
        column: u32,
    ) -> Result<Option<Value>, LspClientError>;

    /// Get hover info at position.
    async fn get_hover(
        &self,
        relative_path: &str,
        line: u32,
        column: u32,
    ) -> Result<Option<Value>, LspClientError>;

    /// Get completions at position.
    async fn get_completions(
        &self,
        relative_path: &str,
        line: u32,
        column: u32,
    ) -> Result<Vec<Value>, LspClientError>;

    /// Get declarations (go-to-definition) at position.
    async fn get_declarations(
        &self,
        relative_path: &str,
        line: u32,
        column: u32,
    ) -> Result<Vec<Value>, LspClientError>;

    /// Get references at position.
    async fn get_references(
        &self,
        relative_path: &str,
        line: u32,
        column: u32,
        include_declaration: bool,
    ) -> Result<Vec<Value>, LspClientError>;

    /// Get document symbols.
    async fn get_document_symbols(&self, relative_path: &str)
        -> Result<Vec<Value>, LspClientError>;

    /// Get code actions for a range.
    async fn get_code_actions(
        &self,
        relative_path: &str,
        start_line: u32,
        start_col: u32,
        end_line: u32,
        end_col: u32,
    ) -> Result<Vec<Value>, LspClientError>;

    /// Resolve a code action to get its edits.
    async fn get_code_action_resolve(&self, action: Value) -> Result<Value, LspClientError>;

    /// Get widgets at position (Lean extension).
    async fn get_widgets(
        &self,
        relative_path: &str,
        line: u32,
        column: u32,
    ) -> Result<Vec<Value>, LspClientError>;

    /// Get widget source by hash (Lean extension).
    async fn get_widget_source(
        &self,
        relative_path: &str,
        line: u32,
        column: u32,
        javascript_hash: &str,
    ) -> Result<Value, LspClientError>;

    /// Shutdown the LSP server.
    async fn shutdown(&self) -> Result<(), LspClientError>;
}

/// Convert a relative file path to a `file://` URI.
pub fn path_to_uri(project_path: &Path, relative_path: &str) -> String {
    let abs = project_path.join(relative_path);
    format!("file://{}", abs.display())
}

/// Convert a `file://` URI back to an absolute [`PathBuf`].
///
/// Returns `None` if the URI does not start with `file://`.
pub fn uri_to_path(uri: &str) -> Option<PathBuf> {
    uri.strip_prefix("file://").map(PathBuf::from)
}

#[cfg(test)]
mod tests {
    use super::*;
    use pretty_assertions::assert_eq;
    use serde_json::json;

    // ── LspClientError Display tests ────────────────────────────────────

    #[test]
    fn test_error_display_transport() {
        let inner = crate::error::TransportError::StdinClosed;
        let err = LspClientError::Transport(inner);
        assert_eq!(format!("{err}"), "Transport error: stdin closed");
    }

    #[test]
    fn test_error_display_lsp_error() {
        let err = LspClientError::LspError {
            code: -32601,
            message: "Method not found".to_string(),
        };
        assert_eq!(format!("{err}"), "LSP error: Method not found");
    }

    #[test]
    fn test_error_display_timeout() {
        let err = LspClientError::Timeout {
            operation: "diagnostics".to_string(),
        };
        assert_eq!(format!("{err}"), "Timeout waiting for diagnostics");
    }

    #[test]
    fn test_error_display_file_not_open() {
        let err = LspClientError::FileNotOpen("Main.lean".to_string());
        assert_eq!(format!("{err}"), "File not open: Main.lean");
    }

    #[test]
    fn test_error_display_not_initialized() {
        let err = LspClientError::NotInitialized;
        assert_eq!(format!("{err}"), "Client not initialized");
    }

    #[test]
    fn test_error_is_send_sync() {
        fn assert_send<T: Send>() {}
        fn assert_sync<T: Sync>() {}
        assert_send::<LspClientError>();
        assert_sync::<LspClientError>();
    }

    // ── URI helper tests ────────────────────────────────────────────────

    #[test]
    fn test_path_to_uri_creates_correct_uri() {
        let project = Path::new("/home/user/my-project");
        let uri = path_to_uri(project, "src/Main.lean");
        assert_eq!(uri, "file:///home/user/my-project/src/Main.lean");
    }

    #[test]
    fn test_path_to_uri_root_file() {
        let project = Path::new("/project");
        let uri = path_to_uri(project, "Foo.lean");
        assert_eq!(uri, "file:///project/Foo.lean");
    }

    #[test]
    fn test_uri_to_path_extracts_correct_path() {
        let path = uri_to_path("file:///home/user/project/Main.lean");
        assert_eq!(path, Some(PathBuf::from("/home/user/project/Main.lean")));
    }

    #[test]
    fn test_uri_to_path_returns_none_for_non_file_uri() {
        assert_eq!(uri_to_path("https://example.com"), None);
        assert_eq!(uri_to_path("ftp://server/file"), None);
        assert_eq!(uri_to_path(""), None);
    }

    // ── MockLspClient tests ─────────────────────────────────────────────

    #[test]
    fn test_mock_client_can_be_created() {
        let _mock = MockLspClient::new();
    }

    #[tokio::test]
    async fn test_mock_client_get_goal_returns_value() {
        let mut mock = MockLspClient::new();
        let goal_value = json!({"goals": ["a : Nat\n|- a = a"]});
        let expected = goal_value.clone();

        mock.expect_get_goal()
            .withf(|path, line, col| path == "Main.lean" && *line == 5 && *col == 0)
            .times(1)
            .returning(move |_, _, _| Ok(Some(goal_value.clone())));

        let result = mock.get_goal("Main.lean", 5, 0).await.unwrap();
        assert_eq!(result, Some(expected));
    }

    #[tokio::test]
    async fn test_mock_client_open_file_succeeds() {
        let mut mock = MockLspClient::new();

        mock.expect_open_file()
            .withf(|path| path == "Foo.lean")
            .times(1)
            .returning(|_| Ok(()));

        let result = mock.open_file("Foo.lean").await;
        assert!(result.is_ok());
    }
}
